# BACKGROUND
background {
    monitor =
    path = /home/irfan/.cache/wallpaper_cache/partial_blur.jpg
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# GREETINGS
label {
    monitor =
    text = Welcome!
    color = rgba(216, 222, 233, .8)
    font_size = 60
    font_family = SF Pro Display Bold
    position = 150, 320
    halign = left
    valign = center
}

# Time
label {
    monitor =
    text = $TIME
    color = rgba(216, 222, 233, .8)
    font_size = 70
    font_family = SF Pro Display Bold
    position = 200, 220
    halign = left
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, .75)
    font_size = 20
    font_family = SF Pro Display Bold
    position = 220, 145
    halign = left
    valign = center
}

# Profie-Photo
image {
    monitor =
    path = ~/.config/Resources/images/PFP.jpg
    border_size = 2
    border_color = rgba(255, 255, 255, .75)
    size = 120
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 260, 0
    halign = left
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 240, 45
    color = rgba(255, 255, 255, .1)
    rounding = -1
    border_size = 0
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)
    position = 200, -160
    halign = left
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = rgba(216, 222, 233, 0.80)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 14
    font_family = SF Pro Display Bold
    position = 255, -160
    halign = left
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 240, 45
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.5 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = Enter Password
    hide_input = false
    position = 200, -230
    halign = left
    valign = center
}
